# Generated by Django 3.1.3 on 2020-12-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewtasks', '0002_task_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_completed', models.CharField(max_length=300)),
            ],
        ),
    ]
